<?php

namespace AppBundle\Repository;

/**
 * GoodNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
