<?php

namespace AppBundle\Repository;

/**
 * ResultNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
